name: dart_kiota
description: "Kiota abstractions for Dart."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  std_uritemplate:
    git:
      url: git@github.com:ricardoboss/std-uritemplate.git
      ref: languages/dart
      path: dart/

dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
