name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Analyze, format, and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub

      - name: Install dependencies
        id: dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        if: steps.dependencies.outcome == 'success'
        run: dart analyze --fatal-infos

      - name: Run build_runner
        if: steps.dependencies.outcome == 'success'
        id: build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        if: steps.build_runner.outcome == 'success'
        run: dart test
